export { CoreApiError, createCoreClient } from "./client";
export type { CoreClientConfig } from "./client";
export type {
  AcceptedRootResponse,
  AddFileTagRequest,
  CreateTagRequest,
  DeleteRequest,
  DeleteTagResponse,
  FileOperationKind,
  FileOperationListResponse,
  FileOperationRecord,
  FileOperationStatus,
  FileOperationsResponse,
  FileTagsResponse,
  FolderRecord,
  ListFileOperationsParams,
  ListFolderChildrenParams,
  ListMediaParams,
  MediaRecord,
  MoveRequest,
  Page,
  RenameRequest,
  RootRecord,
  ScanTaskRequest,
  ScanSummary,
  SearchParams,
  SetFileTagsRequest,
  TagListResponse,
  TagRecord,
  TaskKind,
  TaskRecord,
  TaskStatus,
  ThumbnailAsset,
  ThumbnailResponse,
  UserMetadataRecord,
  UserMetadataUpdate
} from "./generated-contract";
